import { polylendAddress } from '@/config'

export const polylendConfig = {
  address: polylendAddress,
  abi: [
    {
      inputs: [
        {
          internalType: 'address',
          name: '_conditionalTokens',
          type: 'address',
        },
        { internalType: 'address', name: '_usdc', type: 'address' },
        { internalType: 'address', name: '_safeProxyFactory', type: 'address' },
        { internalType: 'address', name: '_feeRecipient', type: 'address' },
      ],
      stateMutability: 'nonpayable',
      type: 'constructor',
    },
    { inputs: [], name: 'AuctionHasEnded', type: 'error' },
    { inputs: [], name: 'AuctionHasNotEnded', type: 'error' },
    { inputs: [], name: 'CollateralAmountIsZero', type: 'error' },
    { inputs: [], name: 'CollateralIsNotApproved', type: 'error' },
    { inputs: [], name: 'InsufficientAllowance', type: 'error' },
    { inputs: [], name: 'InsufficientCollateralBalance', type: 'error' },
    { inputs: [], name: 'InsufficientFunds', type: 'error' },
    { inputs: [], name: 'InvalidCollateralAmount', type: 'error' },
    { inputs: [], name: 'InvalidCollateralAmounts', type: 'error' },
    { inputs: [], name: 'InvalidDuration', type: 'error' },
    { inputs: [], name: 'InvalidLoan', type: 'error' },
    { inputs: [], name: 'InvalidLoanAmount', type: 'error' },
    { inputs: [], name: 'InvalidMinimumDuration', type: 'error' },
    { inputs: [], name: 'InvalidMinimumLoanAmount', type: 'error' },
    { inputs: [], name: 'InvalidOffer', type: 'error' },
    { inputs: [], name: 'InvalidPosition', type: 'error' },
    { inputs: [], name: 'InvalidPositionList', type: 'error' },
    { inputs: [], name: 'InvalidRate', type: 'error' },
    { inputs: [], name: 'InvalidRepayTimestamp', type: 'error' },
    { inputs: [], name: 'LoanAmountExceedsLimit', type: 'error' },
    { inputs: [], name: 'LoanIsCalled', type: 'error' },
    { inputs: [], name: 'LoanIsNotCalled', type: 'error' },
    { inputs: [], name: 'MinimumDurationHasNotPassed', type: 'error' },
    { inputs: [], name: 'MinimumLoanDurationNotMet', type: 'error' },
    { inputs: [], name: 'OnlyBorrower', type: 'error' },
    { inputs: [], name: 'OnlyLender', type: 'error' },
    {
      anonymous: false,
      inputs: [
        { indexed: true, internalType: 'uint256', name: 'id', type: 'uint256' },
        {
          indexed: true,
          internalType: 'uint256',
          name: 'offerId',
          type: 'uint256',
        },
        {
          indexed: true,
          internalType: 'address',
          name: 'borrower',
          type: 'address',
        },
        {
          indexed: false,
          internalType: 'uint256',
          name: 'startTime',
          type: 'uint256',
        },
      ],
      name: 'LoanAccepted',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, internalType: 'uint256', name: 'id', type: 'uint256' },
        {
          indexed: false,
          internalType: 'uint256',
          name: 'callTime',
          type: 'uint256',
        },
      ],
      name: 'LoanCalled',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [{ indexed: true, internalType: 'uint256', name: 'id', type: 'uint256' }],
      name: 'LoanOfferCanceled',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, internalType: 'uint256', name: 'id', type: 'uint256' },
        {
          indexed: true,
          internalType: 'address',
          name: 'lender',
          type: 'address',
        },
        {
          indexed: false,
          internalType: 'uint256',
          name: 'loanAmount',
          type: 'uint256',
        },
        {
          indexed: false,
          internalType: 'uint256',
          name: 'rate',
          type: 'uint256',
        },
      ],
      name: 'LoanOffered',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [{ indexed: true, internalType: 'uint256', name: 'id', type: 'uint256' }],
      name: 'LoanReclaimed',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, internalType: 'uint256', name: 'id', type: 'uint256' },
        {
          indexed: true,
          internalType: 'uint256',
          name: 'offerId',
          type: 'uint256',
        },
      ],
      name: 'LoanRepaid',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: 'uint256',
          name: 'oldId',
          type: 'uint256',
        },
        {
          indexed: true,
          internalType: 'uint256',
          name: 'newId',
          type: 'uint256',
        },
        {
          indexed: true,
          internalType: 'address',
          name: 'newLender',
          type: 'address',
        },
        {
          indexed: false,
          internalType: 'uint256',
          name: 'offerId',
          type: 'uint256',
        },
        {
          indexed: false,
          internalType: 'uint256',
          name: 'newRate',
          type: 'uint256',
        },
      ],
      name: 'LoanTransferred',
      type: 'event',
    },
    {
      inputs: [],
      name: 'MINIMUM_LOAN_DURATION',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'AUCTION_DURATION',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'FEE_PERCENT',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'MAX_INTEREST',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'ONE_HUNDRED_PERCENT',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'PAYBACK_BUFFER',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'uint256', name: '_offerId', type: 'uint256' },
        { internalType: 'uint256', name: '_collateralAmount', type: 'uint256' },
        { internalType: 'uint256', name: '_minimumDuration', type: 'uint256' },
        { internalType: 'uint256', name: '_positionId', type: 'uint256' },
        { internalType: 'bool', name: '_useProxy', type: 'bool' },
      ],
      name: 'accept',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'uint256', name: '_loanId', type: 'uint256' }],
      name: 'call',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'uint256', name: '_id', type: 'uint256' }],
      name: 'cancelOffer',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'conditionalTokens',
      outputs: [
        {
          internalType: 'contract IConditionalTokens',
          name: '',
          type: 'address',
        },
      ],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'feeRecipient',
      outputs: [{ internalType: 'address', name: '', type: 'address' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'uint256', name: '_loanId', type: 'uint256' },
        { internalType: 'uint256', name: '_paybackTime', type: 'uint256' },
      ],
      name: 'getAmountOwed',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'uint256', name: '_offerId', type: 'uint256' }],
      name: 'getOfferCollateralAmounts',
      outputs: [{ internalType: 'uint256[]', name: '', type: 'uint256[]' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'uint256', name: '_offerId', type: 'uint256' }],
      name: 'getOfferPositionIds',
      outputs: [{ internalType: 'uint256[]', name: '', type: 'uint256[]' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      name: 'loans',
      outputs: [
        { internalType: 'uint256', name: 'loanId', type: 'uint256' },
        { internalType: 'address', name: 'borrower', type: 'address' },
        { internalType: 'address', name: 'borrowerWallet', type: 'address' },
        { internalType: 'address', name: 'lender', type: 'address' },
        { internalType: 'uint256', name: 'positionId', type: 'uint256' },
        { internalType: 'uint256', name: 'collateralAmount', type: 'uint256' },
        { internalType: 'uint256', name: 'loanAmount', type: 'uint256' },
        { internalType: 'uint256', name: 'rate', type: 'uint256' },
        { internalType: 'uint256', name: 'startTime', type: 'uint256' },
        { internalType: 'uint256', name: 'minimumDuration', type: 'uint256' },
        { internalType: 'uint256', name: 'callTime', type: 'uint256' },
        { internalType: 'uint256', name: 'offerId', type: 'uint256' },
        { internalType: 'bool', name: 'isTransfered', type: 'bool' },
      ],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'nextLoanId',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'nextOfferId',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'nextRequestId',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'uint256', name: '_loanAmount', type: 'uint256' },
        { internalType: 'uint256', name: '_rate', type: 'uint256' },
        { internalType: 'uint256[]', name: '_positionIds', type: 'uint256[]' },
        {
          internalType: 'uint256[]',
          name: '_collateralAmounts',
          type: 'uint256[]',
        },
        {
          internalType: 'uint256',
          name: '_minimumLoanAmount',
          type: 'uint256',
        },
        { internalType: 'uint256', name: '_duration', type: 'uint256' },
        { internalType: 'bool', name: '_perpetual', type: 'bool' },
      ],
      name: 'offer',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      name: 'offers',
      outputs: [
        { internalType: 'uint256', name: 'offerId', type: 'uint256' },
        { internalType: 'address', name: 'lender', type: 'address' },
        { internalType: 'uint256', name: 'loanAmount', type: 'uint256' },
        { internalType: 'uint256', name: 'rate', type: 'uint256' },
        { internalType: 'uint256', name: 'minimumLoanAmount', type: 'uint256' },
        { internalType: 'uint256', name: 'duration', type: 'uint256' },
        { internalType: 'uint256', name: 'startTime', type: 'uint256' },
        { internalType: 'uint256', name: 'borrowedAmount', type: 'uint256' },
        { internalType: 'bool', name: 'perpetual', type: 'bool' },
      ],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: '', type: 'address' },
        { internalType: 'address', name: '', type: 'address' },
        { internalType: 'uint256[]', name: '', type: 'uint256[]' },
        { internalType: 'uint256[]', name: '', type: 'uint256[]' },
        { internalType: 'bytes', name: '', type: 'bytes' },
      ],
      name: 'onERC1155BatchReceived',
      outputs: [{ internalType: 'bytes4', name: '', type: 'bytes4' }],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: '', type: 'address' },
        { internalType: 'address', name: '', type: 'address' },
        { internalType: 'uint256', name: '', type: 'uint256' },
        { internalType: 'uint256', name: '', type: 'uint256' },
        { internalType: 'bytes', name: '', type: 'bytes' },
      ],
      name: 'onERC1155Received',
      outputs: [{ internalType: 'bytes4', name: '', type: 'bytes4' }],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'uint256', name: '_loanId', type: 'uint256' },
        { internalType: 'bool', name: '_useProxy', type: 'bool' },
      ],
      name: 'reclaim',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'uint256', name: '_loanId', type: 'uint256' },
        { internalType: 'uint256', name: '_repayTimestamp', type: 'uint256' },
      ],
      name: 'repay',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'safeProxyFactory',
      outputs: [
        {
          internalType: 'contract ISafeProxyFactory',
          name: '',
          type: 'address',
        },
      ],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'uint256', name: '_loanId', type: 'uint256' },
        { internalType: 'uint256', name: '_newRate', type: 'uint256' },
      ],
      name: 'transfer',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'usdc',
      outputs: [{ internalType: 'contract ERC20', name: '', type: 'address' }],
      stateMutability: 'view',
      type: 'function',
    },
  ],
} as const
